# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ mainline ]
  pull_request:
    branches: [ mainline ]

jobs:
  job_linux_java8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Clean with Gradle
      run: gradle clean
    - name: Unit test
      run: gradle test
    - name: Build with Gradle
      run: gradle build
  
  job_linux_java11:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Clean with Gradle
      run: gradle clean
    - name: Unit test
      run: gradle test
    - name: Build with Gradle
      run: gradle build
  
  job_windows_java8:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Clean with Gradle
      run: gradle clean
    - name: Unit test
      run: gradle test
    - name: Build with Gradle
      run: gradle build

  job_windows_java11:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Clean with Gradle
      run: gradle clean
    - name: Unit test
      run: gradle test
    - name: Build with Gradle
      run: gradle build

  job_mac_java8:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Clean with Gradle
      run: gradle clean
    - name: Unit test
      run: gradle test
    - name: Build with Gradle
      run: gradle build
  
  job_mac_java11:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Clean with Gradle
      run: gradle clean
    - name: Unit test
      run: gradle test
    - name: Build with Gradle
      run: gradle build
